### ISSUE TITLE
Handle building-less POIs

### ISSUE THREAD

**Issue by joostschouppe** [geometalab/aoi-osm#5]
First step in the process is: "let's find some interesting polygons". If POIs exist as points, but there are no buildings below, then the POIs are simply discarded.
Possible solution: If an interesting node exists with no enclosing polygon, create a buffer around the POI coordinate and work with that polygon.

**Comment by philippks** [comment]
thanks for your input @joostschouppe 

@ANGkeith, the place to implement the recommended solution would be [here](https://github.com/geometalab/aoi-osm/blob/master/webapp/sql/create_pois_view.sql). The first part of the UNION gets all polygons with the POI tags and the second part of the UNION all buildings with a node on it, which have one of the POI tags. Therefore, nodes without a building are not handled (as @joostschouppe correctly pointed out).

Adding a third query to the UNION sounds quick and dirty (especially because the current UNION isn't that nice...). So maybe a split of the query could be considered. Maybe instead using a view, a table can be created which is filled in three steps (polygons with POI tags / buildings with node with POI tags / nodes with POI tags). But this is just an idea.
